# Generated by Django 3.0.3 on 2020-03-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200228_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickers',
            old_name='close_last',
            new_name='close',
        ),
    ]
